FROM continuumio/miniconda3

ENV DEBIAN_FRONTEND=noninteractive 

RUN conda update conda

RUN conda config --add channels bioconda && \
    conda config --add channels conda-forge

RUN conda install -y cellsnp-lite -c bioconda 

RUN pip install vireoSNP
