#!/bin/bash

set -euo pipefail

samplefile=/path/to/sample/file

[[ -e "$samplefile" ]] || (echo "File "$samplefile" not found" && false)

nextflow run main.nf \
  --SAMPLEFILE $samplefile \
  --K donor-value     \
  --ansi-log false \
  -resume
