#!/bin/bash

set -euo pipefail

samplefile=actions/samples.txt

[[ -e "$samplefile" ]] || (echo "File "$samplefile" not found" && false)

nextflow run cellgeni/nf-souporcell \
  --SAMPLEFILE $samplefile \
  --K number-of-donors     \
  --ansi-log false \
  -resume
